import type { Project } from './types';

export const projects: Project[] = [
  {
    id: '1',
    title: '171: O Sonho de Conquistar',
    category: 'curta',
    role: 'Direção e Montagem',
    year: 2025,
    duration: '15 min',
    description: 'O curta-metragem 171: O Sonho de Conquistar busca denunciar como é estar na pele de uma pessoa marginalizada.',
    synopsis: 'O curta-metragem 171: O Sonho de Conquistar busca denunciar como é estar na pele de uma pessoa marginalizada, evidenciando as situações que enfrentam cotidianamente e como lidam com a falta de perspectiva e oportunidades.',
    credits: 'Diretor: Samuel Feitosa\nRoteiro: Guilherme Guimarães\nFotografia: Wellington Lopes\nAssistente de Direção: Maria Vitoria Latorre\nCaptação de Som: Gabriel Frossard\nEditor de Som: Bruno Henrique Machado Gonçalves\nProdução: Rafael Roberto Delvalle, Bruno Henrique Machado Gonçalves\nDireção de Arte: Guilherme Guimarães, João Pedro Cortez\nMontagem: Wendel Bruno',
    thumbnailUrl: 'https://i.imgur.com/hsZNPwI.jpeg',
    videoUrl: 'https://www.youtube.com/watch?v=d4s4KICWfgw',
    featured: true,
  },
  {
    id: '2',
    title: 'Céu, Inferno e Compras Online',
    category: 'curta',
    role: 'Montagem e fotografia',
    year: 2023,
    duration: '3 min',
    description: 'Um garoto tem dúvidas sobre seu encontro, e as coisas pioram quando conselheiros misticos tentam o ajudar.',
    synopsis: 'Um garoto tem dúvidas sobre seu encontro, e as coisas pioram quando conselheiros misticos tentam o ajudar.',
    credits: 'Roteirista: Maria Vitória Latorre\nFotografia: Samuel Feitosa\nCaptação de Som: Bruno Machado Gonçalves\nAtor Anjinho: Guilherme Guimarães\nAtor Menino: Wendel Bruno\nAtor Diabinha: Maria Eduarda\nDireção: Zarzas',
    thumbnailUrl: 'https://i.imgur.com/jEil54x.jpeg',
    videoUrl: 'https://youtu.be/pqaZuhwOVp0',
    featured: false,
  },
  {
    id: '3',
    title: 'Balãozinho de Cria',
    category: 'curta',
    role: 'Ator (Palhaço)',
    year: 2023,
    duration: '6 min',
    description: 'Dois animadores infantis estão atrasados para a entrega de uma festa.',
    synopsis: 'Dois animadores infantis estão atrasados para a entrega de uma festa, quando um deles decide que eles merecem um pouco de diversão alem do trabalho.',
    credits: 'Direção: Wellington Lopes\nAtor Palhaço: Samuel Feitosa\nAtor Animador Infantil: Guilherme Guimarães\nAtriz Menina: Maria Victória Pereira Latorre\nAtor Pai: Bernardo Barcellos\nMaquiagem: Maria Eduarda\nMontadora: Marina Rezende',
    thumbnailUrl: 'https://i.imgur.com/NYCynHC.jpeg',
    videoUrl: 'https://youtu.be/vmYoxhGrVrI',
    featured: false,
  },
  {
    id: '4',
    title: 'ECOCIÊNCIA',
    category: 'serie',
    role: 'Direção de fotografia e Videografismo',
    year: 2025,
    duration: '2 episódios',
    description: 'Dra. Eco e Zé Lixo ensinam como equilibrar ciência e ecologia de uma forma divertida.',
    synopsis: 'Dra. Eco e Zé Lixo ensinam como equilibrar ciência e ecologia de uma forma divertida e prazerosa, sempre com bom humor e com foco na aprendizagem.',
    credits: 'Direção: Clara Luz de Siqueira Carvalho\nDireção de Fotografia: Samuel Feitosa da Silva e Wellington Lopes\nProdução: Maria Victoria Pereira Latorre e Laura Amaral\nEdição/DTV: Gabriel Machado Frossard e Wendel de Sousa Bruno',
    thumbnailUrl: 'https://i.ytimg.com/pl_c/PLCcN-ee4Vrnss_MYrNPBXvUc_1xjU0Rx6/studio_square_thumbnail.jpg?sqp=CK6JxssG-oaymwEICKoDEPABSFqi85f_AwYIvvH2yAY=&rs=AOn4CLCP8SATiUDbGsL3GHw9OwWVxIjWeA',
    videoUrl: '',
    featured: false,
    episodes: [
      { id: 'e4-1', title: 'Episódio 1', synopsis: 'Tratamento da água.', videoUrl: 'https://www.youtube.com/watch?v=PSDrwQ77VRY' },
      { id: 'e4-2', title: 'Episódio 2', synopsis: 'Reciclagem.', videoUrl: 'https://www.youtube.com/watch?v=XqthjW1JtLQ' },
    ]
  },
  {
    id: '10',
    title: 'Derradeiro',
    category: 'curta',
    role: 'Assistência de produção',
    year: 2025,
    duration: '10 min',
    description: 'Sandra enfrenta pesadelos recorrentes que a conectam a feridas ancestrais.',
    synopsis: 'Sandra, uma mulher que acaba de se mudar para o antigo apartamento da avó enfrenta pesadelos recorrentes que a conectam a feridas ancestrais.',
    credits: 'Direção: Ana Clara Paseli\nFotografia: Rafaela Camargo\nMontagem: Alessio Alencar\nAssistentes de Produção: Samuel Feitosa e Bruno Machado Gonçalves\nDireção de Som: Zarzas',
    thumbnailUrl: 'https://i.imgur.com/mVj4ukv.jpeg',
    videoUrl: 'https://youtu.be/gSQQMEAa6xc',
    featured: false,
  },
  {
    id: '13',
    title: 'Arrecadação para Produção do Curta 171',
    category: 'curto',
    role: 'Edição',
    year: 2024,
    duration: '1 min',
    description: 'Bastidores da arrecadação para o projeto 171',
    synopsis: 'Bastidores da arrecadação para o projeto 171',
    credits: 'Edição: Samuel Feitosa',
    thumbnailUrl: 'https://i.imgur.com/HSIRuNf.jpeg',
    videoUrl: 'https://youtube.com/shorts/v4upBr3GY3I',
    featured: false,
  },
  {
    id: '19',
    title: 'Festa de Arrecadação 171',
    category: 'curto',
    role: 'Edição',
    year: 2024,
    duration: '1 min',
    description: 'Festa de arrecadação para produção do curta 171',
    synopsis: 'Festa de arrecadação para produção do curta 171',
    credits: 'Edição: Samuel Feitosa\nNarração: Bruno Machado Gonçalves',
    thumbnailUrl: 'https://i.imgur.com/HSIRuNf.jpeg',
    videoUrl: 'https://youtube.com/shorts/3nLsuGw1ytA',
    featured: false,
  },
  {
    id: '20',
    title: 'Vídeo Curto 3',
    category: 'curto',
    role: 'Edição',
    year: 2024,
    duration: '1 min',
    description: 'Vídeo curto para redes sociais.',
    synopsis: 'Vídeo curto para redes sociais.',
    credits: 'Edição: Samuel Feitosa',
    thumbnailUrl: 'https://i.imgur.com/HSIRuNf.jpeg',
    videoUrl: 'https://youtube.com/shorts/ddk2adx9Swg',
    featured: false,
  },
  {
    id: '14',
    title: 'VideoArte',
    category: 'youtube',
    role: 'Edição',
    year: 2024,
    duration: '1:29 min',
    description: 'Projeto de videoarte.',
    synopsis: 'Projeto de videoarte feito pelos alunos do Senac Santo Amaro.',
    credits: 'Edição: Samuel Feitosa',
    thumbnailUrl: 'https://i.imgur.com/9ude5Dn.jpeg',
    videoUrl: 'https://youtu.be/oZPA9FnWRgU',
    featured: false,
  },
  {
    id: '15',
    title: 'ALEXIA',
    category: 'curta',
    role: 'Assistencia de fotografia e assistencia de som',
    year: 2024,
    duration: 'A definir',
    description: 'Tecnologia e comunicação entre nacionalidades.',
    synopsis: 'O Que aconteceria se 3 pessoas de diferentes nacionalidades dependessem da tecnologia pra se comunicar?',
    credits: 'Direção: Julia Valadares\nMontagem: Alessio Alencar\nFotografia: Rafaela Camargo\nDireção de Som: Gabriel Frossard\nAssistencia de Fotografia: Samuel Feitosa e Bruno Machado',
    thumbnailUrl: 'https://i.imgur.com/Q2XxGC2.jpeg',
    videoUrl: 'https://youtu.be/gSQQMEAa6xc',
    featured: false,
  },
  {
    id: '16',
    title: 'FALTA!',
    category: 'curta',
    role: 'Montador e Ator',
    year: 2023,
    duration: 'A definir',
    description: 'Um jovem se emociona ao lembrar de seu pai.',
    synopsis: 'Ao assistir um Documentário sobre Aviões um jovem se emociona ao lembrar de seu pai',
    credits: 'Direção: Adouglax Scoffield\nMontagem - Ator: Samuel Feitosa',
    thumbnailUrl: '',
    videoUrl: '',
    featured: false,
  },
  {
    id: '17',
    title: 'Recorrendo',
    category: 'serie',
    role: 'Ator e Montador',
    year: 2024,
    duration: '5 episódios',
    description: 'Uma produtora emergente no corre para se destacar.',
    synopsis: 'Conheça a Recorrendo, uma produtora emergente que está no corre para se destacar.',
    credits: 'Diretor: Guilherme Guimarães\nMontador: Samuel Feitosa\nRoteiristas: Guilherme Guimarães e Bruno Machado Gonçalves\nProdução e AD: Maria Victória Latorre\nFotografia: Wellington Lopes\nSom: Wendel Bruno',
    thumbnailUrl: 'https://i.imgur.com/UrQkncs.jpeg',
    videoUrl: '',
    featured: false,
    episodes: [
      { id: 'e17-1', title: 'Episódio 1', synopsis: 'A Equipe do Corre', videoUrl: 'https://youtu.be/mlSMwz27LG4' },
      { id: 'e17-2', title: 'Episódio 2', synopsis: 'Eutam', videoUrl: 'https://youtu.be/-7MvveiiydI' },
      { id: 'e17-3', title: 'Episódio 3', synopsis: 'Conflitos', videoUrl: 'https://youtu.be/tOojhWtqE8M' },
      { id: 'e17-4', title: 'Episódio 4', synopsis: 'Estaca Zero', videoUrl: 'https://youtu.be/h2NVzLEom-I' },
      { id: 'e17-5', title: 'Episódio 5', synopsis: 'Satisfação', videoUrl: 'https://www.youtube.com/watch?v=lnr6d_0cQcQ' },
    ]
  },
];

export async function getProjects(): Promise<Project[]> {
  return Promise.resolve(projects);
}

export async function getFeaturedProject(): Promise<Project | null> {
  return Promise.resolve(projects.find(p => p.featured) || null);
}
